# Generated by Django 3.0.6 on 2020-09-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='Nigeria', max_length=200, null=True),
        ),
    ]
