# Generated by Django 3.0.6 on 2020-07-12 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0004_forumcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcomment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tech.ForumComment'),
        ),
    ]
