# Generated by Django 3.0.6 on 2020-07-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0007_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
