# Generated by Django 3.0.6 on 2020-07-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0008_remove_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='forum_images/')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.Forum')),
            ],
        ),
    ]
