# Generated by Django 3.0.6 on 2020-07-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0010_auto_20200723_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
