# Generated by Django 3.0.6 on 2020-07-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0013_auto_20200729_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='slug',
            field=models.SlugField(editable=False, max_length=200),
        ),
    ]
