# Generated by Django 3.0.6 on 2020-08-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0014_auto_20200729_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
