# Generated by Django 3.0.6 on 2020-08-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0015_auto_20200802_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcomment',
            options={'ordering': ['timestamp']},
        ),
    ]
