# Generated by Django 3.0.6 on 2020-09-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0022_auto_20200912_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='forumimages',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to=''),
        ),
    ]
