# Generated by Django 3.0.6 on 2021-03-03 11:51

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('tech', '0023_auto_20200914_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
